### ISSUE TITLE
Add how to set primary key in documentation

### ISSUE THREAD

**Issue by defrank** [Scille/umongo#116]
I assumed there was no support for specifying a field as a primary key, but all one needs to do is set the `_id` field.  This should be made explicit in the documentation.

Coming from other ORM/ODMs, I figured something more like `email = EmailField(primary_key=True, required=True, unique=True)` was expected.

```python
class User(Document):
    _id = EmailField(required=True, unique=True)
    first_name = StrField()
    last_name = StrField()

    @property
    def email(self):
        return self._id

    @email.setter
    def email(self, value):
        self._id = value
```

**Comment by lafrech** [comment]
See http://umongo.readthedocs.io/en/latest/userguide.html#mongo-world

I believe case 1 can be written.

```python
class User(Document):
    email = EmailField(attribute='_id')
    first_name = StrField()
    last_name = StrField()
```

Does this generate a ReferenceField validation issue? That would be a bug, I guess.

**Comment by touilleMan** [comment]
As @lafrech said, this is already covered

> This almost works which currently works, but ran into validation issues when the object is used in a ReferenceField since _id is not a valid ObjectId.

This however is a nasty little bug ! Can you provide a stacktrace and a test case ?

**Comment by defrank** [comment]
Ah, didn't notice the `attribute` argument.  Perhaps an explicit mention of overriding the primary key could be added in the docs?  Thanks for pointing it out.

Basically my use case:
```python
@instance.register
class Network(Document):
    _id = StrField(required=True, unique=True)

    @property
    def name(self):
        return self._id

    @name.setter
    def name(self, value):
        self._id = value

    class Meta:
        allow_inheritance = True


@instance.register
class NetworkContract(EmbeddedContract):
    network = ReferenceField(Network, required=True)

    class Meta:
        allow_inheritance = True


@instance.register
class Entity(Document):
    emails = ListField(EmailField())
    network_contracts = ListField(EmbeddedField(NetworkContract))

    class Meta:
        allow_inheritance = True


if __name__ ==  '__main__':
    network = Network(_id='facebook')
    network.commit()
    entity = Entity()
    entity.network_contracts.append({'network': network})
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/umongo/data_objects.py", line 25, in append
    obj = self.container_field.deserialize(obj)
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/umongo/abstract.py", line 127, in deserialize
    return super().deserialize(value, attr=attr, data=data)
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/marshmallow/fields.py", line 265, in deserialize
    output = self._deserialize(value, attr, data)
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/umongo/fields.py", line 436, in _deserialize
    raise ValidationError(errors, data=data)
marshmallow.exceptions.ValidationError: {'network': ['Invalid ObjectId.']}
```

In case you don't like that I used a dictionary:
```python
entity.network_contracts.append(NetworkContract(network=network))
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/umongo/embedded_document.py", line 100, in __init__
    self._data = self.DataProxy(kwargs)
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/umongo/data_proxy.py", line 22, in __init__
    self.load(data or {})
  File "/home/derek/Code/fanai-system/venv/lib/python3.6/site-packages/umongo/data_proxy.py", line 101, in load
    raise ValidationError(err)
marshmallow.exceptions.ValidationError: {'network': ['Invalid ObjectId.']}
```

**Comment by lafrech** [comment]
`ReferenceField._deserialize` (here https://github.com/Scille/umongo/blob/master/umongo/fields.py#L284) calls `value = super()._deserialize(value, attr, data)` where `value` is the referenced object's `pk`, and since `Reference` (marshmallow bonus field) inherits from `ObjectId`, `ObjectId._deserialize` is called on the `pk`, which works only if it is an `ObjectId`.

`Reference` field should not inherit from `ObjectId` field.

Not sure how to deal with this. The marshmallow `Reference` field should use the deserialize method of the field corresponding to the type of the `pk` in the referenced document.

**Comment by javdrher** [comment]
Related to this (but not exactly the same): last week we created an additional framework implementation for umongo for a document store other than MongoDB. The code for it is scheduled to be put online somewhere next week. 

We had a couple of issues which we could resolve quite easily, but we also bumped on this issue as the keys are also different from `ObjectId`. We ended up creating our own `ReferenceField` without the `value = super()._deserialize(value, attr, data)` line and some of our own code, because the marshmallow implementation was way too restrictive: deserialization should be field-based or, in our case even implementation based.

**Comment by lomoonmoonbird** [comment]
so is there any solution to this problem

**Comment by Gonzalo933** [comment]
Any update? ran into the same bug

**Comment by lanser-z** [comment]
Encountered the same bug...

**Comment by lafrech** [comment]
I've been trying to work on this.

Modifying `ReferenceField` and `GenericReferenceField` is relatively straightforward, but the generation of the associated marshmallow fields is much more complicated.

I'm open to contributions if anyone is interested in fixing this.

Meanwhile, I shall add a note in the docstring to document the fact that the id should be an ObjectId.

**Comment by lafrech** [comment]
> I'm open to contributions if anyone is interested in fixing this.

No one seems to be willing to work on this and the task is not trivial, so don't expect this to get enhanced any soon.

> Meanwhile, I shall add a note in the docstring to document the fact that the id should be an ObjectId.

I'm happy to merge a doc PR.
