### ISSUE TITLE
Getting the ValidationError without any additional information when inserting documents

### ISSUE THREAD

**Issue by Relrin** [Scille/umongo#130]
Hello,

I'm getting the following error without any description, when doing simple inserts into MongoDB:
```
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/sanic_script/__init__.py", line 350, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/site-packages/sanic_script/__init__.py", line 319, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/sanic_script/commands.py", line 195, in __call__
    return self.run(*args, **kwargs)
  File "/app/app/commands/prepare_mongodb.py", line 36, in run
    loop.run_until_complete(self.create_default_groups())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/app/app/commands/prepare_mongodb.py", line 24, in create_default_groups
    await Group(**data).commit()
  File "/usr/local/lib/python3.6/site-packages/umongo/document.py", line 143, in __init__
    self._data = self.DataProxy(kwargs if kwargs else None)
  File "/usr/local/lib/python3.6/site-packages/umongo/data_proxy.py", line 22, in __init__
    self.load(data or {})
  File "/usr/local/lib/python3.6/site-packages/umongo/data_proxy.py", line 101, in load
    raise ValidationError(err)
marshmallow.exceptions.ValidationError: permissions
```

So, the documents pretty straightforward:
``` python
# groups.py
from umongo import Instance, Document
from umongo.fields import StringField, ListField, ReferenceField

from app import app
from app.permissions.models import Permission

instance = app.config["LAZY_UMONGO"]

@instance.register
class Group(Document):
    name = StringField(allow_none=False, required=True)
    permissions = ListField(ReferenceField(Permission))
# ----------------
# permissions.py
from umongo import Instance, Document
from umongo.fields import StringField

from app import app

instance = app.config["LAZY_UMONGO"]

@instance.register
class Permission(Document):
    codename = StringField(allow_none=False, required=True)
    description = StringField(allow_none=True)

    class Meta:
        indexes = ['$codename', ]
```

And this is the command, that doing stuff for adding data:
```python
class PrepareMongoDbCommand(Command):
    """
    Clean up and fill the MongoDB with default data.
    """
    app = app
    default_groups = [
        {"name": "Game client", "permissions": []},
        {"name": "Game server", "permissions": []},
    ]

    async def create_default_groups(self):
        print("Creating default empty groups...")
        await Group.collection.drop()
        for data in self.default_groups:
            await Group(**data).commit()
        print('Creating has completed!')

    def init_lazy_umongo(self):
        client = AsyncIOMotorClient(self.app.config['MONGODB_URI'])
        database = client[self.app.config['MONGODB_DATABASE']]
        lazy_umongo = self.app.config["LAZY_UMONGO"]
        lazy_umongo.init(database)

    def run(self, *args, **kwargs):
        self.init_lazy_umongo()
        loop = get_event_loop()
        loop.run_until_complete(self.create_default_groups())
```

Any ideas why I'm getting this error and why didn't get any human-readable errors when validation is failing?

**Comment by Relrin** [comment]
Okay, I've figured out what the issue we have here: current state of umongo package isn't compatible with 3.0+ releases of Marchemallow (see issue #129). So, now just replace dependency onto something like `marshmallow==2.15.0` and everything will work good.

**Comment by lafrech** [comment]
Yes, MA3 is not stable yet.

Since it is tagged beta, `pip` should stick to v2 unless you pass the `--pre` option.
