### ISSUE TITLE
Error while commiting a document using motor asyncio

### ISSUE THREAD

**Issue by OneWithNoFace** [Scille/umongo#164]
I tried using umongo with motor asyncio by simple python code:
```
import asyncio

from motor.motor_asyncio import AsyncIOMotorClient

from umongo import Document, fields, Instance

instance = None
db = AsyncIOMotorClient()['asdf']
instance = Instance(db)


@instance.register
class User(Document):
    name = fields.StrField(required=True)

async def insert():
    user = User(name='aasadf')
    await user.commit()

asyncio.get_event_loop().run_until_complete(insert())
```

But it throws this Exception:
StackTrace:
`Traceback (most recent call last):
  File "motor_test.py", line 20, in <module>
    asyncio.get_event_loop().run_until_complete(insert())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "motor_test.py", line 18, in insert
    await user.commit()
  File "/home/harsh/headstart/umongo/umongo/frameworks/motor_asyncio.py", line 149, in commit
    ret = yield from self.collection.insert_one(payload)
  File "/home/harsh/.local/lib/python3.6/site-packages/motor/metaprogramming.py", line 52, in method
    return framework.future_or_callback(future, callback, loop)
AttributeError: module 'motor.frameworks.asyncio' has no attribute 'future_or_callback'
`

**Comment by OneWithNoFace** [comment]
Issue was with Motor.
