### ISSUE TITLE
While running app at GCloud Ubuntu 18.04, I am gettin DBRef import error

### ISSUE THREAD

**Issue by binrebin** [Scille/umongo#232]
I am deploying an App with umongo2.2. see the traceback:
```
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from auth import SiteHandler
  File "/home/marryapp_dev/app/mapp-server/backend/auth.py", line 6, in <module>
    from umongo import ValidationError
  File "/home/marryapp_dev/app/aioenv/lib/python3.6/site-packages/umongo/__init__.py", line 2, in <module>
    from .instance import Instance
  File "/home/marryapp_dev/app/aioenv/lib/python3.6/site-packages/umongo/instance.py", line 3, in <module>
    from .document import DocumentTemplate
  File "/home/marryapp_dev/app/aioenv/lib/python3.6/site-packages/umongo/document.py", line 3, in <module>
    from bson import DBRef
ImportError: cannot import name 'DBRef'
```
Anybody help.

**Comment by lafrech** [comment]
Do you have pymongo installed? Which version?

Please run `pip freeze`.

**Comment by lafrech** [comment]
Closing as inactive. Please comment if you're still stuck.
