### ISSUE TITLE
Unknown document class when using ReferenceField

### ISSUE THREAD

**Issue by crinny** [Scille/umongo#287]
Hello! I am trying to use umongo in my project and I want to separate the document definition and database initialization as in #97. This is my code:
```python
# core/models/game.py
from umongo import PyMongoInstance, Document, fields

from core.models.user import User

instance = PyMongoInstance()


@instance.register
class Game(Document):
    started_at = fields.DateTimeField()
    players = fields.ListField(fields.ReferenceField(User))

    class Meta:
        collection_name = "game"
```

```python
# core/models/user.py
from umongo import PyMongoInstance, Document, fields

instance = PyMongoInstance()


@instance.register
class User(Document):
    user_id = fields.IntegerField(unique=True)
    first_name = fields.StringField()
    last_name = fields.StringField(allow_none=True)
    username = fields.StringField(allow_none=True)

    class Meta:
        collection_name = "user"
```

```python
# core/database.py
from datetime import datetime

from pymongo import MongoClient

import core.models.user as user
import core.models.game as game

db = MongoClient().test

user.instance.init(db)
game.instance.init(db)

test_user = user.User(user_id=1, first_name="Test", last_name=None, username="Test")
test_user.commit()

game.Game(
    started_at=datetime.now(),
    players=[
        test_user
    ],
).commit()
```

After running the `database.py` file, the user document is created in the database, but game one isn't. I am getting the following error:

```
umongo.exceptions.NotRegisteredDocumentError: Unknown document class `User`
```

<details>
  <summary>Full traceback</summary>
  
  ```
Traceback (most recent call last):
  File "C:/Users/crinny/PycharmProjects/falsemafia/core/database.py", line 21, in <module>
    some_gay
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\document.py", line 144, in __init__
    self._data = self.DataProxy(kwargs)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\data_proxy.py", line 22, in __init__
    self.load(data or {})
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\data_proxy.py", line 102, in load
    loaded_data, err = self.schema.load(data, partial=True)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\marshmallow\schema.py", line 588, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\marshmallow\schema.py", line 670, in _do_load
    index_errors=self.opts.index_errors,
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\marshmallow\marshalling.py", line 290, in deserialize
    index=(index if index_errors else None)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\marshmallow\marshalling.py", line 63, in call_and_store
    value = getter_func(data)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\marshmallow\marshalling.py", line 283, in <lambda>
    data
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\abstract.py", line 191, in deserialize
    return super().deserialize(value, attr=attr, data=data)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\marshmallow\fields.py", line 265, in deserialize
    output = self._deserialize(value, attr, data)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\fields.py", line 307, in _deserialize
    elif isinstance(value, self.document_cls):
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\fields.py", line 289, in document_cls
    self._document_cls = self.instance.retrieve_document(self.document)
  File "C:\Users\crinny\PycharmProjects\falsemafia\venv\lib\site-packages\umongo\instance.py", line 54, in retrieve_document
    'Unknown document class `%s`' % name_or_template)
umongo.exceptions.NotRegisteredDocumentError: Unknown document class `User`
```
  
</details>

System information:
 - Windows 10
 - umongo version: 2.2.0
 - pymongo version: 3.10.1
 - Python version: 3.7.7

**Comment by lafrech** [comment]
You must use the same instance for all your models.

You need to share the instance object across your model files.
